### ISSUE TITLE
Packaging issue: lib/index.js does not exist

### ISSUE THREAD

**Issue by ajmas** [Randagio13/countries-states-cities-service#11]
We are building our project using vite and we get the following issue:

> Error: Failed to resolve entry for package "countries-states-cities-service". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "countries-states-cities-service". The package may have incorrect main/module/exports specified in its package.json.

Looking at `package.json`, it makes reference to `lib/index.js`, yet in `node_modules/countries-states-cities-service/lib` there is no `index.js`. Instead it is in the `src` sub folder.

It looks like the packaging or references need to be fixed up.

This impacts version 1.3.2

**Comment by Randagio13** [comment]
Hi @ajmas, thank you for your help.

Let me check, I'll get back to you asap.

**Comment by Randagio13** [comment]
Hi @ajmas, did you try last version? it should work. Let me know

**Comment by ajmas** [comment]
I haven't. I'll check as soon as I get a chance.

**Comment by ajmas** [comment]
I was just able to give this a go. 

Using the current head (2266ad40f285bb703b25e7f36e473ab0c27dcc12) I am still seeing the issue.

Checking `package.json`:

```json
  "typings": "lib/index.d.ts",
  "module": "lib/index.js",
  "exports": "./lib/index.js",
```

Build steps:

```sh
npm install
npm run build
```

Looking at generated lib folder:

```
babel.config.d.ts
babel.config.d.ts.map
babel.config.js
babel.config.js.map
jest.config.d.ts
jest.config.d.ts.map
jest.config.js
jest.config.js.map
src
tsconfig.tsbuildinfo
```

Looking at generated lib/src folder:

```
index.d.ts
index.d.ts.map
index.js
index.js.map
```
