### ISSUE TITLE
Packaging issue: lib/index.js does not exist (2)

### ISSUE THREAD

**Issue by ajmas** [Randagio13/countries-states-cities-service#13]
Opening this ticket since issue #11 wasn't actually properly resolved. I have since added a PR to that issue, that should fix the underlying problem.

**Comment by ammo8600** [comment]
Just installed it seems like the issue hasn't been resolved.

**Comment by ajmas** [comment]
@ammo8600 the PR is still pending a merge. Hopefully @Randagio13 will be able to deal with it before year end.

**Comment by Randagio13** [comment]
Hi guys, sorry I missed the PR and the issue, I will take a look in these day. Thanks! Merry Christmas 🎄

**Comment by Randagio13** [comment]
#12 Released!Thanks @ajmas 🙌🏻

**Comment by ajmas** [comment]
I'll test it out in a bit to make sure it works. @ammo8600 can you check too please

**Comment by ajmas** [comment]
I just tried building my project, using 1.3.4 release, and it seems okay. Thanks
